### ISSUE TITLE
文件上传 超过1M上传不了 

### ISSUE THREAD

**Issue by peterzcl** [halo-sigs/plugin-alioss#17]
![image](https://user-images.githubusercontent.com/28745693/223910219-8aa5d1a4-bdcb-4bae-bd5b-19802796784d.png)
1M一下秒传  1M以上就一直不行

**Comment by guqing** [comment]
需要提供更多的信息帮助我们判断：
1. halo 版本号
2. 生产环境部署还是本地部署
3. 是否使用 nginx
4. 浏览器控制台有没有错误日志，或者 halo 有没有相关错误日志提供一下

/triage needs-information

**Comment by peterzcl** [comment]
Halo Vsesion: 2.3.0

**Comment by peterzcl** [comment]
感谢  排查了下 是第三个问题413 Request Entity Too Large  nginx文件上传最大1了
