### ISSUE TITLE
阿里云 Endpoint 配置不正确导致无法正常显示图片

### ISSUE THREAD

**Issue by llllike** [halo-sigs/plugin-alioss#5]
这个字段一定不要带https://
![QQ图片20221208172459](https://user-images.githubusercontent.com/100058012/206408986-2be97075-0f19-45f2-9060-f14524a1b20b.png)
如果带了https:// 图片能上传到阿里云，阿里云控制台也能正常打开图片，但是halo网页无法显示图片

**Comment by ruibaby** [comment]
/kind improvement

可以考虑优化一下，加一个校验。

**Comment by JohnNiang** [comment]
[plugin-alioss 1.0.1](https://github.com/halo-sigs/plugin-alioss/releases/tag/v1.0.1) 已经解决了这个问题，可下载测试。

/close

**Comment by longjuan** [comment]
@JohnNiang 呃呃，我的那个PR好像没对endpoint做验证，只对domain做了验证。
另外我发现如果endpoint没加上协议头，他自动会加上`http`的协议头，如下图
![image](https://user-images.githubusercontent.com/28662535/208658353-9a8f3388-7ea6-401a-a246-ebba51197fe4.png)
如果要做验证是否在buildClient的时候额外加上`https://`更安全，还是说再给一个协议选择的设置来控制？

**Comment by JohnNiang** [comment]
Hi @longjuan ，从官方文档和源码上看，设置 endpoint 时，可以加上 protocol，并且优先级比 client 的 protocol 更高。不过为了更加安全，可以试着设置以下 client 的 protocol 为 https：

```java
    OSS buildOss(AliOssProperties properties) {
        var config = new ClientBuilderConfiguration();
        config.setProtocol(Protocol.HTTPS);
        return OSSClientBuilder.create()
            .endpoint(properties.getEndpoint())
            .credentialsProvider(new DefaultCredentialProvider(properties.getAccessKey(),
                properties.getAccessSecret()))
            .clientConfiguration(config)
            .build() ;
    }
```

**Comment by longjuan** [comment]
> Hi @longjuan ，从官方文档和源码上看，设置 endpoint 时，可以加上 protocol，并且优先级比 client 的 protocol 更高。不过为了更加安全，可以试着设置以下 client 的 protocol 为 https：
> 
> ```java
>     OSS buildOss(AliOssProperties properties) {
>         var config = new ClientBuilderConfiguration();
>         config.setProtocol(Protocol.HTTPS);
>         return OSSClientBuilder.create()
>             .endpoint(properties.getEndpoint())
>             .credentialsProvider(new DefaultCredentialProvider(properties.getAccessKey(),
>                 properties.getAccessSecret()))
>             .clientConfiguration(config)
>             .build() ;
>     }
> ```

好的，我来提个PR？
